### HL2 ###

ladfighter.hl2.alyx=アリックス・ヴァンス
ladfighter.hl2.barney=バーニー・カルフーン
ladfighter.hl2.dog=ＤØＧ
ladfighter.hl2.kleiner=アイザック・クライナー
ladfighter.hl2.magnusson=アルネ・マグナッソン
ladfighter.hl2.eli=イーライ・ヴァンス
ladfighter.hl2.mossman=ジュディス・モスマン
ladfighter.hl2.breen=ウォレス・ブリーン
ladfighter.hl2.fisherman=漁師
ladfighter.hl2.vort=ヴォーティガント
ladfighter.hl2.uriah=ウリヤ
ladfighter.hl2.monk=グリゴリ 神父

ladfighter.hl2.c17.van=バン
ladfighter.hl2.c17.ted=テッド
ladfighter.hl2.c17.joe=ジョー
ladfighter.hl2.c17.eric=エリック
ladfighter.hl2.c17.art=アート
ladfighter.hl2.c17.sandro=サンドロ
ladfighter.hl2.c17.mike=マイク
ladfighter.hl2.c17.vance=ファンス
ladfighter.hl2.c17.erdin=エルディン
ladfighter.hl2.c17.andrew=アンドリュー

ladfighter.hl2.c17.joey=ジョーイ
ladfighter.hl2.c17.kanisha=カニシャ
ladfighter.hl2.c17.kim=キム
ladfighter.hl2.c17.chau=チャウ
ladfighter.hl2.c17.naomi=ナオミ
ladfighter.hl2.c17.lakeetra=ラケートラ

ladfighter.hl2.antlion=アントライオン
ladfighter.hl2.antlionguard=アントライオンガード
ladfighter.hl2.police=国民保護
ladfighter.hl2.policeelite=エリート国民保護
ladfighter.hl2.soldier=北軍兵士
ladfighter.hl2.elite=北軍のエリート兵士
ladfighter.hl2.zombine=ゾンビ